name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

env:
  binary: bevy-minesweeper
  add_binaries_to_github_release: true
  use_git_lfs: false

jobs:

  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: olegtarasov/get-tag@v2.1.2
        id: get_version
      - name: Create Release
        id: create
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.get_version.outputs.tag }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-linux:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - uses: olegtarasov/get-tag@v2.1.2
        id: get_version
      - uses: actions/checkout@v4
        with:
          lfs: ${{ env.use_git_lfs }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v2
      - run: sudo apt-get update && sudo apt-get install -y pkg-config libx11-dev libasound2-dev libudev-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Build
        run: cargo build --release --target x86_64-unknown-linux-gnu --no-default-features

      - name: Prepare package
        run: |
          mkdir linux
          # copy only top-level files, skip subdirs
          find target/x86_64-unknown-linux-gnu/release -maxdepth 1 -type f -exec cp {} linux/ \;
          cp -r assets linux/ || true

      - name: Package as a zip
        working-directory: ./linux
        run: zip --recurse-paths ../${{ env.binary }}.zip .

      - uses: actions/upload-artifact@v4
        with:
          path: ${{ env.binary }}.zip
          name: linux
          retention-days: 1

      - name: Upload to release
        if: ${{ env.add_binaries_to_github_release == 'true' }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./${{ env.binary }}.zip
          asset_name: ${{ env.binary }}-linux-${{ steps.get_version.outputs.tag }}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-windows:
    runs-on: windows-latest
    needs: create-release
    steps:
      - uses: olegtarasov/get-tag@v2.1.2
        id: get_version
      - uses: actions/checkout@v4
        with:
          lfs: ${{ env.use_git_lfs }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-gnu
      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release --target x86_64-pc-windows-gnu --no-default-features

      - name: Prepare package
        shell: pwsh
        run: |
          mkdir windows
          Get-ChildItem -Path target/x86_64-pc-windows-gnu/release -File | Copy-Item -Destination windows/
          if (Test-Path assets) { Copy-Item assets windows -Recurse }

      - name: Package as a zip
        run: Compress-Archive -Path windows/* -DestinationPath ${{ env.binary }}.zip

      - uses: actions/upload-artifact@v4
        with:
          path: ${{ env.binary }}.zip
          name: windows
          retention-days: 1

      - name: Upload to release
        if: ${{ env.add_binaries_to_github_release == 'true' }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./${{ env.binary }}.zip
          asset_name: ${{ env.binary }}-windows-${{ steps.get_version.outputs.tag }}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-macOS-intel:
    runs-on: macOS-latest
    needs: create-release
    steps:
      - uses: olegtarasov/get-tag@v2.1.2
        id: get_version
      - uses: actions/checkout@v4
        with:
          lfs: ${{ env.use_git_lfs }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin
      - uses: Swatinem/rust-cache@v2
      - run: |
          export CFLAGS="-fno-stack-check"
          export MACOSX_DEPLOYMENT_TARGET="10.9"

      - name: Build
        run: cargo build --release --target x86_64-apple-darwin --no-default-features

      - name: Prepare package
        run: |
          mkdir -p ${{ env.binary }}.app/Contents/MacOS
          find target/x86_64-apple-darwin/release -maxdepth 1 -type f -exec cp {} ${{ env.binary }}.app/Contents/MacOS/ \;
          cp -r assets ${{ env.binary }}.app/Contents/MacOS/ || true
          hdiutil create -fs HFS+ -volname "${{ env.binary }}" -srcfolder ${{ env.binary }}.app ${{ env.binary }}-macOS-intel.dmg

      - uses: actions/upload-artifact@v4
        with:
          path: ${{ env.binary }}-macOS-intel.dmg
          name: macOS-intel
          retention-days: 1

      - name: Upload to release
        if: ${{ env.add_binaries_to_github_release == 'true' }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./${{ env.binary }}-macOS-intel.dmg
          asset_name: ${{ env.binary }}-macOS-intel-${{ steps.get_version.outputs.tag }}.dmg
          asset_content_type: application/x-apple-diskimage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-macOS-apple-silicon:
    runs-on: macOS-latest
    needs: create-release
    steps:
      - uses: olegtarasov/get-tag@v2.1.2
        id: get_version
      - uses: actions/checkout@v4
        with:
          lfs: ${{ env.use_git_lfs }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin
      - uses: Swatinem/rust-cache@v2
      - run: export MACOSX_DEPLOYMENT_TARGET="11"

      - name: Build
        run: cargo build --release --target aarch64-apple-darwin --no-default-features

      - name: Prepare package
        run: |
          mkdir -p ${{ env.binary }}.app/Contents/MacOS
          find target/aarch64-apple-darwin/release -maxdepth 1 -type f -exec cp {} ${{ env.binary }}.app/Contents/MacOS/ \;
          cp -r assets ${{ env.binary }}.app/Contents/MacOS/ || true
          hdiutil create -fs HFS+ -volname "${{ env.binary }}-macOS-apple-silicon" -srcfolder ${{ env.binary }}.app ${{ env.binary }}-macOS-apple-silicon.dmg

      - uses: actions/upload-artifact@v4
        with:
          path: ${{ env.binary }}-macOS-apple-silicon.dmg
          name: macOS-apple-silicon
          retention-days: 1

      - name: Upload to release
        if: ${{ env.add_binaries_to_github_release == 'true' }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./${{ env.binary }}-macOS-apple-silicon.dmg
          asset_name: ${{ env.binary }}-macOS-apple-silicon-${{ steps.get_version.outputs.tag }}.dmg
          asset_content_type: application/x-apple-diskimage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
